[tools]
python = "latest"

[tasks.journey_west]
run = "python -m src.browser https://browser.engineering/examples/xiyouji.html"

[tasks.emoji]
run = "python -m src.browser 'data:text/html,ðŸ˜…ðŸ™ƒðŸ¥³ðŸ¥º'"

[tasks.text]
run = "python -m src.browser https://browser.engineering/text.html"

[tasks.test]
run = "python -m unittest"

[env]
_.python.venv = { path = ".venv", create = true }
