[tools]
python = "latest"

[tasks.journey_west]
run = "python -m src.browser https://browser.engineering/examples/xiyouji.html"

[tasks.text]
run = "python -m src.browser https://browser.engineering/text.html"

[tasks.size]
run = "python -m src.browser 'data:text/html,<html>this is <big>BIG</big> and <small>small</small> text</html>'"

[tasks.blocks]
run = "python -m src.browser 'data:text/html,<p>This is block 1</p><p>This is block 2</p>'"

[tasks.test]
run = "python -m unittest"

[tasks.font_style]
run = "python -m src.browser 'data:text/html,This is <b>bold</b> and <i>Italic text</i>'"

[tasks.parser]
run = "python -m src.browser https://browser.engineering/html.html"

[tasks.layout]
run = "python -m src.browser https://browser.engineering/layout.html"

[tasks.comment]
run = 'python -m src.browser "data:text/html,<p>cool markup</p><!-- cool comment -->"'

[tasks.links]
run = 'python -m src.browser "data:text/html,<nav>This should have no background</nav><nav class="links">This shoud have a gray background</nav>"'

[tasks.entities]
run = '''
python -m src.browser "data:text/html,
<p>This should be a less then char: &lt;</p>
<p>This should just be an amp: &</p> 
<p>This should be a copyright: &copy</p> 
<p>This should be a copyright: &copy;</p> 
<p>This should be a heart: &hearts;</p> 
<p>This should be a div src: &lt;div&gt;</p>" 
'''

[env]
_.python.venv = { path = ".venv", create = true }
