[tools]
python = "latest"

[tasks.journey_west]
run = "python -m src.browser https://browser.engineering/examples/xiyouji.html"

[tasks.emoji]
run = "python -m src.browser 'data:text/html,ðŸ˜…ðŸ™ƒðŸ¥³ðŸ¥º'"

[tasks.text]
run = "python -m src.browser https://browser.engineering/text.html"

[tasks.size]
run = "python -m src.browser 'data:text/html,this is <big>BIG</big> and <small>small</small> text'"

[tasks.test]
run = "python -m unittest"

[tasks.font_style]
run = "python -m src.browser 'data:text/html,This is <b>bold</b> and <i>Italic text</i>'"

[tasks.parser]
run = "python -m src.browser https://browser.engineering/html.html"

[env]
_.python.venv = { path = ".venv", create = true }
